routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/getUserNotifications', 'NotificationsController@getUserNotifications')->name('getUserNotifications');
// Mark Notifications as read
Route::post('/readUserNotification', 'NotificationsController@show')->name('readUserNotification');
// Mark All Notifications as read
Route::post('/readAllUserNotification', 'NotificationsController@showAll')->name('readAllUserNotification');
    
Route::get('/', 'LeadController@create');
Route::post('addlead', 'LeadController@store')->name('addlead');

Route::group([
		'prefix'	=> 'dashboard',
	], function(){
		Route::get('/', 'DashboardController@index');
		Route::resource('lead', 'LeadController');
		Route::get('leadData', 'LeadController@leadData')->name('leadData');
		Route::resource('studio', 'StudioController');
});


Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

resources/views/createlead.blade.php
@extends('layouts.mainapp')

@section('content')
    <div  style="background-size: contain;min-height: 100%;height: 100%;padding: 6% 2rem 1rem 2rem; background-image: url('{{ asset('images/media/signup_bg.png') }}')" class="main-wrapper" >
        <div class="container">
            <div class="row">
                <div class="col-xl-7 justify-content-center mx-auto text-center">
                    <div class="sg-card card">
                        <div class="main-body main-signupbody">
                            <div class="row">
                                <div class="card-body about-con pabout">
                                    <div class="col-md-12 col-lg-12 ">
                                        <a href="{{ url('/') }}"><img src="{{ asset('images/brand/logo.png') }}" class="header-brand-img desktop-logo " alt="Dashlot logo"></a>
                                        <div class="smhr"></div>
                                        <h6>I’m ready to Test the Theory</h6>
                                    	<form id="leadform">
                                    		@csrf
                                    		<div class="row">
                                    			<div class="col-md-6">
                                    				<div class="form-group">
                                    					<input type="text" class="form-control" name="first_name" placeholder="First Name">
                                    				</div>
                                    			</div>
                                    			<div class="col-md-6">
                                    				<div class="form-group">
                                    					<input type="text" class="form-control" name="last_name" placeholder="Last Name">
                                    				</div>
                                    			</div>
                                    		</div>
                                    		<div class="row">
                                    			<div class="col-md-12">
                                    				<div class="form-group">
                                    					<input type="text" class="form-control" name="number" placeholder="Phone Number">
                                    				</div>
                                    			</div>
                                    		</div>
                                    		<div class="row">
                                    			<div class="col-md-12">
                                    				<div class="form-group">
                                    					<input type="email" class="form-control" name="email" placeholder="Email">
                                    				</div>
                                    			</div>
                                    		</div>
                                    		<div class="row">
                                    			<div class="col-md-12">
                                                    <div class="std-slc" style="text-align: left;">
                                                        <label style="display: inline-block;width: 100%;" class="std-sc">Studio Selection</label>
                                                    </div>
                                                    <div class="radio_series row">
                                    			    	@foreach($studios as $studio)
                                                        <div class="col-md-4 col-lg-4">
                                        			    	<label class="custom-control custom-radio ">
                                        							<input type="radio" class="custom-control-input" name="studio[]" value="{{ $studio->id }}" >
                                        							<span class="custom-control-label">{{ $studio->name }}</span>
                                        					</label>
                                                        </div>
                                    			        @endforeach
                                                    </div>
                                			    </div>
                                	        </div>
                                	        <div class="row">
                                    			<div class="col-md-12">
                                					<div class="mt-2 mb-2">
                                						<button id="form-btn" type="submit" class="msubb btn btn-primary btn-lg">Submit Form <i class="fa fa-arrow-right"></i></button>
                                					</div>
                                				</div>
                                			</div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('title')
Sign Up
@endsection
@push('scripts')
	<script type="text/javascript">
		$.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
		$('#form-btn').on('click', function() {

			event.preventDefault();

		 	$('#form-btn').prop("disabled", true);
            $('#form-btn').html("Loading <i class='fa fa-spin fa-spinner'></i>");
            var formData = new FormData($('#leadform')[0]);
            $.ajax({
                url: '{{ route('addlead') }}',
                type: 'POST',
                dataType: 'JSON',
                data: formData,
                contentType: false,
                cache: false,
                processData: false,
                success:function(data){
                    $('#leadform').trigger('reset');
                    $('#form-btn').html("Submit");
                    $('#form-btn').removeAttr("disabled");
                    toastr.success('Request has been submitted');
                    setTimeout(function(){
                       window.location.reload(1);
                    }, 3000);
                },
                error:function(data, statusText, xhdr){
                    var errors = data.responseJSON.errors;
                    var message = '';
                    $.each(errors,function(index, val) {
                        message += val[0]+'<br />';
                    });
                    toastr.error(message);
                    $('#form-btn').html("Submit");
                    $('#form-btn').removeAttr("disabled");
                }
            });
		});
	</script>
@endpush
{{-- <lead-from studios="{{ $studios }}"></lead-from> --}}

resources/views/dashboard.blade.php
@extends('layouts.dashboardLayout')

@section('content')


<div style="margin: 142px 0px 1.5rem;">
    
</div>

<div class="row ">
    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <div class="card overflow-hidden">
            <div class="card-body">
                <div class="d-flex">
                    <div class="">
                        <p class="mb-2 h6">Total Submission</p>
                        <h2 class="mb-1 ">{{ count($leads) }}</h2>
                        {{-- <p class="mb-0 text-muted"><span class="text-success">(+0.35%)<i class="fe fe-arrow-up text-success"></i></span>Increase</p> --}}
                    </div>
                    <div class=" my-auto ml-auto">
                        <div class="chart-wrapper text-center">
                            <img src="{{ asset('images/media/charticon.png') }}">
                            {{-- <canvas id="areaChart1" class="areaChart2 chartjs-render-monitor chart-dropshadow-primary overflow-hidden mx-auto"></canvas> --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <div class="card overflow-hidden">
            <div class="card-body">
                <div class="d-flex">
                    <div class="">
                        <p class="mb-2 h6"><i class="fa fa-map-marker"></i> {{ $studiolead->studio->name }}</p>
                        <h2 class="mb-1 ">{{ $studioleadsTotal }}</h2>
                        <p class="mb-0"><span>Most Submission</span></p>
                    </div>
                    <div class=" my-auto ml-auto">
                        <div class="chart-wrapper">
                            <img src="{{ asset('images/media/charticon2.png') }}">
                            {{-- <canvas id="areaChart2" class="areaChart2 chartjs-render-monitor chart-dropshadow-secondary overflow-hidden"></canvas> --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->

<!-- row opened -->
<div class="row">
    <div class="col-lg-8 col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Single line chart</h3>
                <div class="card-options">
                    <a href="#" class="card-options-fullscreen" data-toggle="card-fullscreen"><i class="fe fe-maximize"></i></a>
                </div>
            </div>
            <div class="card-body">
                <div id="echart7" class="chartsh h-300"></div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Studios</h3>
                <div class="card-options">
                    <a href="#" class="card-options-fullscreen" data-toggle="card-fullscreen"><i class="fe fe-maximize"></i></a>
                </div>
            </div>
            <div class="">
                <div class="table-responsive">
                    <table class="dstable table card-table border table-bordered text-nowrap">  
                        <tbody>
                            @if(count($studios) > 0)
                                @foreach($studios as $studio)
                                <tr>
                                    <td>{{ $studio->name }}</th>
                                    <td>{{ $studio->id}}</td>
                                </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- row closed -->

<!-- row opened -->
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Latest Lead Form</div>
                <div class="card-options">
                    <a style="color: #09B0EC;font-size: 15px;text-decoration: underline;" href="{{ route('lead.index') }}">View All</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive ">
                    <table class="studioListingTable table table-bordered border-top table-hover mb-0 text-nowrap">
                            <thead>
                                <tr>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Phone</th>
                                    <th>Email Address</th>
                                    <th>Studio Name</th>
                                    <th>Date Submission</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(count($leads) > 0)
                                    @foreach($leads as $lead)
                                    <tr>
                                        <td>{{ $lead->first_name }}</th>
                                        <td>{{ $lead->last_name}}</td>
                                        <td>{{ $lead->number }}</td>
                                        <td>{{ $lead->email }}</td>
                                        <td>{{ $lead->studio->name }}</td>
                                        <td>{{ $lead->created_at }}</td>
                                    </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                </div>
            </div>
            <!-- table-wrapper -->
        </div>
        <!-- section-wrapper -->
    </div>
</div>
<!-- row closed -->
@endsection
@section('title')
Dashboard
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/leadListing.blade.php
@extends('layouts.dashboardLayout')

@section('content')


<!-- row opened -->
<div class="page-header">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#"><i class="ti-package mr-1"></i> Lead Form</a></li>
    </ol>
    <div class="mt-3 mt-lg-0">
        <div class="d-flex align-items-center flex-wrap text-nowrap">
            <button id="exportbtn" style="background: #CA373D;    border-color: rgba(249, 72, 89, 0.3); box-shadow: 0 5px 10px rgba(249, 72, 89, 0.3) !important;" type="button" class="btn btn-success btn-icon-text mr-2 d-none d-md-block">
                <i class="fe fe-download"></i>
                Export
            </button>
            <button id="printbtn" style="background-color: #36b37e; border-color: #36b37e; box-shadow: 0 5px 10px rgba(19, 191, 166, 0.3) !important;" type="button" class="btn btn-secondary btn-icon-text mr-2 mb-2 mb-md-0">
                <i class="fe fe-printer"></i>
                Print
            </button>
            <button id="pdfbtn" type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0">
                <i class="fe fe-download-cloud "></i>
                Download Report
            </button>
        </div>
    </div>
</div>

<!-- row opened -->
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Lead</div>
                <div class="card-options">
                    <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                    <a href="#" class="card-options-fullscreen" data-toggle="card-fullscreen"><i class="fe fe-maximize"></i></a>
                    <a href="#" class="card-options-remove" data-toggle="card-remove"><i class="fe fe-x"></i></a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive ">
                    <table id="myDataTable" class="table table-striped table-bordered text-nowrap">
                        <thead>
                            <tr>
                                <th class="wd-15p border-bottom-0">First name</th>
                                <th class="wd-15p border-bottom-0">Last name</th>
                                <th class="wd-20p border-bottom-0">Phone Number</th>
                                <th class="wd-15p border-bottom-0">Email</th>
                                <th class="wd-10p border-bottom-0">Studio Name</th>
                                <th class="wd-25p border-bottom-0">Date Submission</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- table-wrapper -->
        </div>
        <!-- section-wrapper -->
    </div>
</div>
<!-- row closed -->
@endsection
@section('title')
Lead Listing
@endsection
@push('scripts')
<script>
    $(document).ready(function() {
        // alert('HELLO');
        $('#myDataTable').DataTable({
            processing: true,
            serverSide: true,
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ],
            ajax: '{{ route('leadData') }}',
            columns: [
                {data: 'first_name', name: 'first_name'},
                {data: 'last_name', name: 'last_name'},
                {data: 'number', name: 'number'},
                {data: 'email', name: 'email'},
                {data: 'studio_id', name: 'studio_id'},
                {data: 'created_at', name: 'created_at'},
        ]
        });
    });
</script>
<script type="text/javascript">
    $('#exportbtn').on('click', function() {
        $('.buttons-excel').trigger( "click" );
    });
    $('#printbtn').on('click', function() {
        $('.buttons-print').trigger( "click" );
    });
    $('#pdfbtn').on('click', function() {
        $('.buttons-pdf').trigger( "click" );
    });
</script>
@endpush

resources/views/studioListing.blade.php
@extends('layouts.dashboardLayout')

@section('content')


<!-- row opened -->
<div class="page-header">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#"><img style="width: 18px;" src="{{ asset('images/media/icon-nav-black.png') }}"> Studio</a></li>
    </ol>
    <div class="mt-3 mt-lg-0">
        <div class="d-flex align-items-center flex-wrap text-nowrap">
            <button data-toggle="modal" data-target="#addStudioModal" type="button" class="btn btn-primary btn-icon-text mb-2 mb-md-0">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                Add Studio
            </button>
        </div>
    </div>
</div>

<!-- row opened -->
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="card">
            <div class="">
                <div class="table-responsive">
                    <div class="dataTables_wrapper studioTableWarapper">
                        <table class="studioListingTable table table-bordered border-top table-hover mb-0 text-nowrap">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Studio Name</th>
                                    <th>Email Address</th>
                                    <th style="text-align: center;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(count($studios) > 0)
                                    @foreach($studios as $studio)
                                    <tr>
                                        <th style="text-align: center;" scope="row">{{ $studio->id }}</th>
                                        <td>{{ $studio->name }}</td>
                                        <td>{{ $studio->email }}</td>
                                        <td align="center"><button data-edit-action="{{ route('studio.edit', $studio->id ) }}" data-update-action="{{ route('studio.update', $studio->id ) }}" type="button" id="edit-btn" class="editbtn btn btn-primary btn-icon-text mb-2 mb-md-0" data-toggle="modal" data-target="#editStudioModal" >Edit</button>
                                            <form style="display: inline-block;" action="{{route('studio.destroy', $studio->id ) }}" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button type="submit"  id="delete-btn" class="delete-btn btn btn-primary btn-icon-text mb-2 mb-md-0"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                        <div class="dataTables_paginate paging_simple_numbers" id="myDataTable_paginate">
                            {{ $studios->links() }}
                        </div>
                    </div>
                </div>
            </div>
            <!-- table-wrapper -->
        </div>
        <!-- section-wrapper -->
    </div>
</div>
<!-- row closed -->

<div class="modal fade addStudioModal" id="addStudioModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                {{-- <h5 class="modal-title" id="example-Modal3">New message</h5> --}}
                <img src="{{ asset('images/brand/logo.jpg') }}" class="header-brand-img desktop-logo " alt="Dashlot logo">
                <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="createStudioForm">
                    @csrf
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Studio Name">
                    </div>
                    <div class="">
                        <input type="text" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div class="footerbtn">
                    <button type="button" id="addStudioBtn" class="addStudioBtn btn btn-primary">Save Changes <i class="fa fa-arrow-right"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade editStudioModal" id="editStudioModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                {{-- <h5 class="modal-title" id="example-Modal3">New message</h5> --}}
                <img src="{{ asset('images/brand/logo.jpg') }}" class="header-brand-img desktop-logo " alt="Dashlot logo">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="updateStudioForm">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Studio Name">
                    </div>
                    <div class="">
                        <input type="text" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div class="footerbtn">
                    <button data-update-action="" type="button" id="UpdateStudioBtn" class="UpdateStudioBtn btn btn-primary">Update Changes <i class="fa fa-arrow-right"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('title')
Studio Listing
@endsection
@push('scripts')
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $('#addStudioBtn').on('click', function() {
            event.preventDefault();

            $('#addStudioBtn').prop("disabled", true);
            $('#addStudioBtn').html("Loading <i class='fa fa-spin fa-spinner'></i>");
            var formData = new FormData($('#createStudioForm')[0]);
            $.ajax({
                url: '{{ route('studio.store') }}',
                type: 'POST',
                dataType: 'JSON',
                data: formData,
                contentType: false,
                cache: false,
                processData: false,
                success:function(data){
                    $('#createStudioForm').trigger('reset');
                    $('#addStudioBtn').html("Submit");
                    $('#addStudioBtn').removeAttr("disabled");
                    $('#addStudioModal').modal('hide');
                    toastr.success('Request has been submitted');
                    setTimeout(function(){
                       window.location.reload(1);
                    }, 2000);
                },
                error:function(data, statusText, xhdr){
                    var errors = data.responseJSON.errors;
                    var message = '';
                    $.each(errors,function(index, val) {
                        message += val[0]+'<br />';
                    });
                    toastr.error(message);
                    $('#addStudioBtn').html("Submit");
                    $('#addStudioBtn').removeAttr("disabled");
                }
            });
        });
    </script>
    <script type="text/javascript">
        $('.editbtn').on('click', function(){
            var editAction = $(this).data('edit-action');
            var updateAction = $(this).data('update-action');
            $.ajax({
                url: editAction,
                type: 'GET',
                dataType: 'JSON',
                success:function(data){
                    $('.editStudioModal #name').val(data.name);
                    $('.editStudioModal #email').val(data.email);
                    $('.editStudioModal #UpdateStudioBtn').attr('data-update-action', updateAction);
                    // console.log(data);
                },
                error:function(data, statusText, xhdr){
                    var errors = data.responseJSON.errors;
                    var message = '';
                    $.each(errors,function(index, val) {
                        message += val[0]+'<br />';
                    });
                    toastr.error(message);
                    $('#editbtn').html("Submit");
                    $('#editbtn').removeAttr("disabled");
                }
            });
        });
        $('#UpdateStudioBtn').on('click', function(){
            $('#UpdateStudioBtn').prop("disabled", true);
            $('#UpdateStudioBtn').html("Loading <i class='fa fa-spin fa-spinner'></i>");
            var updateAction = $(this).data('update-action');
            var formData = new FormData($('#updateStudioForm')[0]);
            $.ajax({
                url: updateAction,
                type: 'POST',
                data: formData,
                dataType: 'JSON',
                contentType: false,
                cache: false,
                processData: false,
                success:function(data){
                    $('#UpdateStudioBtn').html("Submit");
                    $('#UpdateStudioBtn').removeAttr("disabled");
                    $('#addStudioModal').modal('hide');
                    toastr.success('Request has been updated');
                    setTimeout(function(){
                       window.location.reload(1);
                    }, 2000);
                },
                error:function(data, statusText, xhdr){
                    var errors = data.responseJSON.errors;
                    var message = '';
                    $.each(errors,function(index, val) {
                        message += val[0]+'<br />';
                    });
                    toastr.error(message);
                    $('#UpdateStudioBtn').html("Submit");
                    $('#UpdateStudioBtn').removeAttr("disabled");
                }
            });
        });
    </script>
@endpush